name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout master
    - uses: actions/checkout@master
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        repository: nico385412/book-api
        tags: latest